// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function FuzzySearch(arg1, arg2) {
  return window['go']['main']['App']['FuzzySearch'](arg1, arg2);
}

export function GetAvailableShortcuts() {
  return window['go']['main']['App']['GetAvailableShortcuts']();
}

export function GetBatteryInfo() {
  return window['go']['main']['App']['GetBatteryInfo']();
}

export function GetBlockDevices() {
  return window['go']['main']['App']['GetBlockDevices']();
}

export function GetCPUInfo() {
  return window['go']['main']['App']['GetCPUInfo']();
}

export function GetCPULoad() {
  return window['go']['main']['App']['GetCPULoad']();
}

export function GetCPUSpeed() {
  return window['go']['main']['App']['GetCPUSpeed']();
}

export function GetCPUTemperature() {
  return window['go']['main']['App']['GetCPUTemperature']();
}

export function GetClockHours() {
  return window['go']['main']['App']['GetClockHours']();
}

export function GetCurrentUsername() {
  return window['go']['main']['App']['GetCurrentUsername']();
}

export function GetDiskUsage(arg1) {
  return window['go']['main']['App']['GetDiskUsage'](arg1);
}

export function GetExternalIP() {
  return window['go']['main']['App']['GetExternalIP']();
}

export function GetExternalIPWithGeo() {
  return window['go']['main']['App']['GetExternalIPWithGeo']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetHardwareInfo() {
  return window['go']['main']['App']['GetHardwareInfo']();
}

export function GetIPGeoLocation(arg1) {
  return window['go']['main']['App']['GetIPGeoLocation'](arg1);
}

export function GetMediaData(arg1) {
  return window['go']['main']['App']['GetMediaData'](arg1);
}

export function GetMemoryInfo() {
  return window['go']['main']['App']['GetMemoryInfo']();
}

export function GetNetworkConnections() {
  return window['go']['main']['App']['GetNetworkConnections']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetNetworkStats(arg1) {
  return window['go']['main']['App']['GetNetworkStats'](arg1);
}

export function GetPDFData(arg1) {
  return window['go']['main']['App']['GetPDFData'](arg1);
}

export function GetProcessCount() {
  return window['go']['main']['App']['GetProcessCount']();
}

export function GetProcessList() {
  return window['go']['main']['App']['GetProcessList']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsData() {
  return window['go']['main']['App']['GetSettingsData']();
}

export function GetShortcuts() {
  return window['go']['main']['App']['GetShortcuts']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetUptime() {
  return window['go']['main']['App']['GetUptime']();
}

export function HandleShortcut(arg1) {
  return window['go']['main']['App']['HandleShortcut'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ResolveFilePath(arg1, arg2) {
  return window['go']['main']['App']['ResolveFilePath'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateShortcut(arg1) {
  return window['go']['main']['App']['UpdateShortcut'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
