// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function CheckForUpdates():Promise<models.UpdateInfo>;

export function FuzzySearch(arg1:string,arg2:string):Promise<Array<models.SearchResult>>;

export function GetAvailableShortcuts():Promise<Record<string, string>>;

export function GetBatteryInfo():Promise<models.BatteryInfo>;

export function GetBlockDevices():Promise<Array<models.BlockDevice>>;

export function GetCPUInfo():Promise<models.CPUInfo>;

export function GetCPULoad():Promise<models.CPULoad>;

export function GetCPUSpeed():Promise<models.CPUSpeed>;

export function GetCPUTemperature():Promise<models.CPUTemperature>;

export function GetClockHours():Promise<number>;

export function GetCurrentUsername():Promise<string>;

export function GetDiskUsage(arg1:string):Promise<models.DiskUsage>;

export function GetExternalIP():Promise<models.ExternalIP>;

export function GetExternalIPWithGeo():Promise<models.IPGeoInfo>;

export function GetFileInfo(arg1:string):Promise<models.FileInfo>;

export function GetHardwareInfo():Promise<models.HardwareInfo>;

export function GetIPGeoLocation(arg1:string):Promise<models.GeoLookupResult>;

export function GetMediaData(arg1:string):Promise<models.MediaData>;

export function GetMemoryInfo():Promise<models.MemoryInfo>;

export function GetNetworkConnections():Promise<Array<models.NetworkConnection>>;

export function GetNetworkInfo():Promise<models.NetworkInfo>;

export function GetNetworkStats(arg1:string):Promise<Array<models.NetworkStats>>;

export function GetPDFData(arg1:string):Promise<models.MediaData>;

export function GetProcessCount():Promise<models.ProcessCount>;

export function GetProcessList():Promise<models.ProcessList>;

export function GetSettings():Promise<models.Settings>;

export function GetSettingsData():Promise<Record<string, any>>;

export function GetShortcuts():Promise<Array<models.Shortcut>>;

export function GetSystemInfo():Promise<models.SystemInfo>;

export function GetTheme():Promise<main.Theme>;

export function GetUptime():Promise<number>;

export function HandleShortcut(arg1:string):Promise<string>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Ping(arg1:string):Promise<models.PingResult>;

export function ReadDirectory(arg1:string):Promise<models.DirectoryData>;

export function ReadFile(arg1:string):Promise<models.FileData>;

export function ResolveFilePath(arg1:string,arg2:string):Promise<string>;

export function UpdateSettings(arg1:Record<string, any>):Promise<void>;

export function UpdateShortcut(arg1:models.Shortcut):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
